apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo3
  labels:
    app: demo3
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo3
  template:
    metadata:
      labels:
        app: demo3
    spec:
      containers:
      - image: 192.168.0.216:8888/library/demo3:v1
        name: demo3
      restartPolicy: Always

